---
- hosts: all
  tasks:
  - name: 1) return network info
    shell: ip addr
    register: result
  - name: print network info
    debug: 
      var: result.stdout
  - name: 2) return network info
    shell: ip addr
    register: result
  - name: print network info
    debug: 
      var: result.stdout
  - name: 3) return network info
    shell: ip addr
    register: result
  - name: print network info
    debug: 
      var: result.stdout
  - name: 4) return network info
    shell: ip addr
    register: result
  - name: print network info
    debug: 
      var: result.stdout
